### PR TITLE
Add redis 7

### PR DESCRIPTION
**Pull request by hhorak**
This is a pre-work, likely a bit too early, because we don't have redis 7 even in Fedora (it's in 37 that we don't have s2i-core for). However, there is a hope we will be able just to remove `.exclude-*` files once we have RPMs there.

For the case there are some more changes and we need to rebase this PR, these were the steps done:

```
git mv 6 7
git commit -m "[1/3] Add redis v7

First step is just a move, to keep the git history in the latest version."
cp -r 7 6
git add 6
git commit -m "[2/3] Add redis v7

Copy content from 7 to 6, keeping the git history in 7"
sed -i -e 's/redis-6/redis-7/' -e 's/redis6/redis7/' -e 's/VERSION=6/VERSION=7/'  -e 's/Redis 6/Redis 7/' Dockerfile* root/usr/libexec/container-setup root/usr/share/container-scripts/redis/README.md
sed -i -e 's|quay.io/fedora/s2i-core:34|quay.io/fedora/s2i-core:37|' Dockerfile.fedora 
git commit -am "[3/3] Add redis v7

Change version in the 7/ directory where needed"
git rm Dockerfile.rhel7 Dockerfile
git commit -am "Remove Dockerfile.rhel7 and Dockerfile as there are no plans for redis 7 on rhel-7"
touch .exclude-rhel8 .exclude-rhel9 .exclude-c9s .exclude-c8s .exclude-fedora
git add .exclude-*
git commit -m "Add exclude files for OS versions we don't have redis for yet (all for now)"
```

### CODE REVIEW

**Comment by hhorak** [comment]
[test]

**Comment by hhorak** [comment]
@phracek thanks, I always forget about this... hope it's fixed now.

**Comment by phracek** [comment]
@hhorak Thanks for adding it. BUT If you plan to test this PR also for V7, then first of all you have to add into workflows and then in this pull request, you will be able to run tests also for V7.

I have already done it https://github.com/sclorg/redis-container/pull/136

**Comment by hhorak** [comment]
[test]

**Comment by phracek** [comment]
[test-openshift]

**Review by phracek — APPROVED** [review]
Thanks for the PR! I did not hit any issues.

**Comment by phracek** [comment]
Can you please update also the main README.md? I did not hit this. But It can be done as a separate pull request.

**Comment by hhorak** [comment]
Thanks for the review. The README.md in the root is now updated.
[test-all]

**Comment by phracek** [comment]
[test-openshift]

**Review by phracek — APPROVED** [review]
LGTM. I did not hit any issues.

**Pull request merged**
