### PR TITLE
Support redis-container on Quay.io

### PR DESCRIPTION
**Pull request by phracek**
This commit uses Quay.io register instead of Docker.io

Fixes: https://github.com/sclorg/redis-container/issues/69

### CODE REVIEW

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test][test-openshift]

**Comment by phracek** [comment]
[test][test-openshift]

**Comment by ljavorsk** [comment]
LGTM, however, I don't have experience with the functions ``ct_os*`` so I don't know if those changes are valid

**Review by ljavorsk — COMMENTED** [review]
LGTM, however, I don't have experience with the functions ``ct_os*`` so I don't know if those changes are valid

**Pull request merged**
