### PR TITLE
Layer all versions on s2i-core

### PR DESCRIPTION
**Pull request by pkubatrh**
Does not introduce any source to image functionality yet.

### CODE REVIEW

**Comment by pkubatrh** [comment]
Not adding the same changes to Dockerfile.fedora yet because https://github.com/sclorg/s2i-base-container/issues/144

**Comment by omron93** [comment]
I would wait for s2i-core image to be built in Fedora and do this change also for Fedora Dockerfile in one PR.

**Comment by hhorak** [comment]
s2i-core image is built in fedora now (f26 and f27), but not yet available in registry.fedoraproject.org registry.

**Comment by hhorak** [comment]
It's available as `candidate-registry.fedoraproject.org/f26/s2i-core` only at this point.

**Comment by hhorak** [comment]
There is a separate PR for Fedora #27, so we can merge this one I believe.

**Pull request merged**
