### PR TITLE
add redis 5 sources for rhel7 and centos7

### PR DESCRIPTION
**Pull request by pkubatrh**

### CODE REVIEW

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
[test]

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
rhel7-openshift failures should be fixed by https://github.com/sclorg/container-common-scripts/pull/124

**Comment by pkubatrh** [comment]
centos7 openshift tests failing as the image is not available on dockerhub yet. As the image will only be available when it is built by the CI after merging this PR we should ignore the test case failure in case the image is not available.

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
[test][test-openshift]

**Comment by pkubatrh** [comment]
Seems like there was some kind of error when starting to bring the openshift cluster up on the rhel7 machine: https://gist.github.com/rhscl-bot/61559423be389835e97dbf050a34bb64#file-redis-container-16-sh-L2108

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
[test-openshift]

**Comment by pkubatrh** [comment]
Tests green now. @hhorak PTAL when you have time

**Comment by hhorak** [comment]
LGTM

**Comment by pkubatrh** [comment]
Thanks for the review! Merging

**Pull request merged**
