### PR TITLE
[1/2] Deprecate version Redis 5 for RHEL-8

### PR DESCRIPTION
**Pull request by ljavorsk**

### CODE REVIEW

**Comment by ljavorsk** [comment]
I was not sure what should be removed in `imagestreams/redis-centos.json`.

Also please take a look into all image streams, if they are correctly removed.

I'll update this PR when I have some review about the image streams.

**Comment by phracek** [comment]
I would prefer this variant. We have agreed to deprecate imagestreams around two month ago before EOL. Would it be possible to separate this PR into two PRs?
One for image streams and the second one for the rest.
In the case of imagestreams, add also redis-centos.json. When we are deprecating RHEL7, then CentOS 7 is deprecated as well.

**Comment by ljavorsk** [comment]
Separate PR for imagestreams: https://github.com/sclorg/redis-container/pull/103

**Comment by phracek** [comment]
[test-all]

**Comment by ljavorsk** [comment]
The deprecation has been done in commit [88e88ecd3320c810726214853fa914288c87335b](https://github.com/sclorg/redis-container/commit/88e88ecd3320c810726214853fa914288c87335b)

**Pull request closed without merging**
