### PR TITLE
Add imagestream generator

### PR DESCRIPTION
**Pull request by phracek**
No custom tag is needed, as far as I know.

### CODE REVIEW

**Comment by phracek** [comment]
[test-openshift]

**Comment by phracek** [comment]
Redis-7 is already available for RHEL-9 so enable imagestream tests.

[test-openshift]

**Comment by phracek** [comment]
Only two remaining based on https://github.com/sclorg/container-common-scripts/issues/364

**Comment by phracek** [comment]
[test-openshift]

**Comment by phracek** [comment]
[test-openshift]

**Review by zmiklank — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
