### PR TITLE
Add v6

### PR DESCRIPTION
**Pull request by hhorak**
Redis v6 is currently available only in Fedora.

### CODE REVIEW

**Comment by hhorak** [comment]
CI fails with 'Error: Failed to download metadata for repo 'updates': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried' - I guess some temporary infra issue.

**Comment by hhorak** [comment]
@remicollet What do you think?

**Comment by hhorak** [comment]
> Thanks for the PR!. Would it be possible to add also version 6 into main README.md file https://github.com/sclorg/redis-container/blob/master/README.md#versions

Oh, sure, will fix shortly. Thanks for noticing it.

**Comment by hhorak** [comment]
I deliberately did not change examples, because we do not have RHEL 7 and CentOS 7 images available at this point.

**Comment by phracek** [comment]
[test][test-openshift]

**Pull request merged**
