### PR TITLE
Enable building and testing redis-7 for C9S and RHEL9.

### PR DESCRIPTION
**Pull request by phracek**
Enable building and testing redis-7 for C9S and RHEL9.

For RHEL9 devel-repo is used.

### CODE REVIEW

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
CentOS Stream 9 still installs `redis-6`>

```bash
CentOS Stream 9 - Extras packages                34 kB/s |  12 kB     00:00    
Dependencies resolved.
================================================================================
 Package                 Arch        Version               Repository      Size
================================================================================
Installing:
 policycoreutils         x86_64      3.5-1.el9             baseos         238 k
 redis                   x86_64      6.2.7-1.el9           appstream      1.3 M
Installing dependencies:
 acl                     x86_64      2.3.1-3.el9           baseos          73 k
```

**Comment by phracek** [comment]
RHEL 9 still installs `redis-6`:


```bash
Red Hat Universal Base Image 9 (RPMs) - CodeRea 1.1 MB/s | 195 kB     00:00    
Dependencies resolved.
================================================================================
 Package          Arch   Version         Repository                        Size
================================================================================
Installing:
 policycoreutils  x86_64 3.5-1.el9       rhel-9-for-x86_64-baseos-rpms    242 k
 redis            x86_64 6.2.7-1.el9     rhel-9-for-x86_64-appstream-rpms 1.3 M
Installing dependencies:
```

**Comment by phracek** [comment]
[test]

**Comment by hhorak** [comment]
We can add development c9s compose to have redis:7 available, see https://github.com/sclorg/s2i-nodejs-container/pull/400/commits/b698e26e243cd634ff4dcd3f16f568188c8b7d5c for inspiration.

I also see as not ideal the fact that despite a wrong version is installed, the image gets build successfully, let's rather check the version right in the Dockerfile - filed as a separate PR: https://github.com/sclorg/redis-container/pull/149

**Comment by phracek** [comment]
> We can add development c9s compose to have redis:7 available, see [sclorg/s2i-nodejs-container@b698e26](https://github.com/sclorg/s2i-nodejs-container/commit/b698e26e243cd634ff4dcd3f16f568188c8b7d5c) for inspiration.

What about to do it on Testing Farm part. In case it is .devel-repo then we can add this CentOS 9 stream repo automatically.

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
[test]

**Comment by phracek** [comment]
Let's try if RPMs are already in COMPOSEs

[test]

**Comment by phracek** [comment]
Let's try if RPMs are already in COMPOSEs

[test]

**Comment by phracek** [comment]
> We can add development c9s compose to have redis:7 available, see [sclorg/s2i-nodejs-container@b698e26](https://github.com/sclorg/s2i-nodejs-container/commit/b698e26e243cd634ff4dcd3f16f568188c8b7d5c) for inspiration.
> 
> I also see as not ideal the fact that despite a wrong version is installed, the image gets build successfully, let's rather check the version right in the Dockerfile - filed as a separate PR: #149

@hhorak I totally forgot, that on C9S and RHEL9 are modules. By this commit https://github.com/sclorg/redis-container/pull/146/commits/a48ba88540f71f5be837bc31ee34db801b1c5978 I have enabled.

**Comment by phracek** [comment]
@hhorak Everything is GREEN.

**Pull request merged**
